### ISSUE TITLE
Jelyfin Version Notes

### ISSUE THREAD

**Issue by IonCharge** [parallelspec/qnapJellyfinArm#1]
Hi, 

Would like to add something of note: 

ARM CPU versions of QNAP currently have very old Linux Kernel Versions (4.2.8) even on QTS 5.0+. QNAP has not addressed this issue yet. Link to Kernel list: https://www.qnap.com/en-us/release-notes/kernel#:~:text=QNAP%20Switch%20System%20(QSS)%20is%20the%20configuration%20interface%20for

The last version of Jellyfin that is supported by this kernel is version 10.8.13. This is due to newer versions using a .Net8

This issue was referenced in: https://github.com/jellyfin/jellyfin/issues/12436

You may want to update your documentation to pull 'linuxserver/jellyfin:10.8.13' 

[10.8.13](https://hub.docker.com/layers/linuxserver/jellyfin/10.8.13/images/sha256-7494a15e9eff0865d3c15a0be5049448d64087236270689dc71c19ff4c32a66d?context=explore)

**Comment by parallelspec** [comment]
Thanks for the heads-up, will update. What a shame though.
